# Generated by Django 5.2.7 on 2025-10-13 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(verbose_name='是否正確')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作答時間')),
            ],
            options={
                'verbose_name': '作答紀錄',
                'verbose_name_plural': '作答紀錄',
                'db_table': 'attempt',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='收藏時間')),
            ],
            options={
                'verbose_name': '收藏',
                'verbose_name_plural': '收藏',
                'db_table': 'bookmark',
            },
        ),
        migrations.CreateModel(
            name='ExamQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(verbose_name='題目順序')),
                ('points', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='配分')),
            ],
            options={
                'verbose_name': '考卷題目',
                'verbose_name_plural': '考卷題目',
                'db_table': 'exam_question',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='筆記內容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '筆記',
                'verbose_name_plural': '筆記',
                'db_table': 'note',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100, verbose_name='科目')),
                ('category', models.CharField(max_length=50, verbose_name='題型分類')),
                ('content', models.TextField(verbose_name='題目內容')),
                ('explanation', models.TextField(blank=True, verbose_name='解析')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已發布')], default='draft', max_length=20, verbose_name='狀態')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
            ],
            options={
                'verbose_name': '題目',
                'verbose_name_plural': '題目',
                'db_table': 'question',
            },
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='選項內容')),
                ('is_correct', models.BooleanField(default=False, verbose_name='是否為正確答案')),
            ],
            options={
                'verbose_name': '題目選項',
                'verbose_name_plural': '題目選項',
                'db_table': 'question_option',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='標籤名稱')),
            ],
            options={
                'verbose_name': '標籤',
                'verbose_name_plural': '標籤',
                'db_table': 'tag',
            },
        ),
    ]
