# Generated by Django 5.2.7 on 2025-11-24 03:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0006_add_question_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EssayGrading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='得分')),
                ('max_score', models.DecimalField(decimal_places=2, default=100.0, max_digits=5, verbose_name='滿分')),
                ('feedback', models.TextField(verbose_name='總體評語')),
                ('strengths', models.TextField(blank=True, null=True, verbose_name='優點')),
                ('weaknesses', models.TextField(blank=True, null=True, verbose_name='缺點')),
                ('suggestions', models.TextField(blank=True, null=True, verbose_name='改進建議')),
                ('grading_method', models.CharField(choices=[('ai', 'AI 批改'), ('manual', '人工批改')], default='ai', max_length=20, verbose_name='批改方式')),
                ('graded_at', models.DateTimeField(auto_now_add=True, verbose_name='批改時間')),
            ],
            options={
                'verbose_name': '申論題批改',
                'verbose_name_plural': '申論題批改',
                'db_table': 'essay_grading',
                'ordering': ['-graded_at'],
            },
        ),
        migrations.CreateModel(
            name='EssaySubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_year', models.IntegerField(verbose_name='考試年度')),
                ('question_text', models.TextField(verbose_name='題目內容')),
                ('answer_text', models.TextField(verbose_name='答案內容')),
                ('status', models.CharField(choices=[('pending', '待批改'), ('grading', '批改中'), ('completed', '已完成')], default='pending', max_length=20, verbose_name='狀態')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='提交時間')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '申論題提交',
                'verbose_name_plural': '申論題提交',
                'db_table': 'essay_submission',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='考試別名稱')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='代碼')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '考試別',
                'verbose_name_plural': '考試別',
                'db_table': 'exam_series',
            },
        ),
        migrations.CreateModel(
            name='ExamSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='年度')),
                ('session', models.CharField(default='第一試', max_length=20, verbose_name='場次')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '年度場次',
                'verbose_name_plural': '年度場次',
                'db_table': 'exam_session',
            },
        ),
        migrations.CreateModel(
            name='QuestionSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='科目名稱（舊資料）')),
                ('question_type', models.CharField(default='選擇題', max_length=20, verbose_name='題型')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '題組',
                'verbose_name_plural': '題組',
                'db_table': 'question_set',
            },
        ),
        migrations.CreateModel(
            name='StudyRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_type', models.CharField(choices=[('subject_focus', '科目重點'), ('weak_area', '弱項加強'), ('practice_schedule', '練習安排'), ('review_reminder', '複習提醒'), ('exam_prep', '考試準備')], max_length=30, verbose_name='建議類型')),
                ('priority', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高'), ('urgent', '緊急')], default='medium', max_length=20, verbose_name='優先級')),
                ('content', models.TextField(verbose_name='建議內容')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='生成時間')),
                ('is_read', models.BooleanField(default=False, verbose_name='已讀')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='閱讀時間')),
            ],
            options={
                'verbose_name': '學習建議',
                'verbose_name_plural': '學習建議',
                'db_table': 'study_recommendation',
                'ordering': ['-priority', '-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='開始時間')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='結束時間')),
                ('duration', models.IntegerField(default=0, verbose_name='持續時間（秒）')),
                ('questions_attempted', models.IntegerField(default=0, verbose_name='答題數量')),
                ('accuracy', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='正確率')),
            ],
            options={
                'verbose_name': '學習時段',
                'verbose_name_plural': '學習時段',
                'db_table': 'study_session',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='科目名稱')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='科目代碼')),
                ('category', models.CharField(default='general', max_length=50, verbose_name='分類')),
                ('description', models.TextField(blank=True, null=True, verbose_name='說明')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '科目',
                'verbose_name_plural': '科目',
                'db_table': 'subject',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(verbose_name='是否正確')),
                ('time_spent', models.IntegerField(default=0, verbose_name='花費時間（秒）')),
                ('attempt_count', models.IntegerField(default=1, verbose_name='嘗試次數')),
                ('last_attempt_at', models.DateTimeField(auto_now=True, verbose_name='最後嘗試時間')),
                ('mastery_level', models.CharField(choices=[('novice', '初學'), ('beginner', '入門'), ('intermediate', '中等'), ('advanced', '進階'), ('master', '精通')], default='novice', max_length=20, verbose_name='熟練度')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '使用者進度',
                'verbose_name_plural': '使用者進度',
                'db_table': 'user_progress',
                'ordering': ['-last_attempt_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='attempt',
            options={'ordering': ['-created_at'], 'verbose_name': '作答記錄', 'verbose_name_plural': '作答記錄'},
        ),
        migrations.AlterModelOptions(
            name='questionoption',
            options={'ordering': ['order'], 'verbose_name': '題目選項', 'verbose_name_plural': '題目選項'},
        ),
        migrations.RemoveIndex(
            model_name='question',
            name='question_status_15e17e_idx',
        ),
        migrations.RemoveIndex(
            model_name='question',
            name='question_categor_101460_idx',
        ),
        migrations.RenameIndex(
            model_name='question',
            new_name='question_questio_d42815_idx',
            old_name='question_question_7a6c62_idx',
        ),
        migrations.RenameIndex(
            model_name='question',
            new_name='question_difficu_1f5c54_idx',
            old_name='question_difficulty_c4d86f_idx',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='questions',
        ),
        migrations.AddField(
            model_name='questionoption',
            name='order',
            field=models.IntegerField(default=0, verbose_name='順序'),
        ),
        migrations.AddField(
            model_name='tag',
            name='category',
            field=models.CharField(default='general', max_length=50, verbose_name='分類'),
        ),
        migrations.AddField(
            model_name='tag',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='question_bank.question'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='selected_options',
            field=models.ManyToManyField(blank=True, related_name='attempts', to='question_bank.questionoption', verbose_name='選擇的選項'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='question_bank.question'),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='note',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='question_bank.question'),
        ),
        migrations.AlterField(
            model_name='note',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_questions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, null=True, verbose_name='解析'),
        ),
        migrations.AlterField(
            model_name='questionoption',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='question_bank.question'),
        ),
        migrations.AddField(
            model_name='essaysubmission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='essay_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='essaygrading',
            name='essay_submission',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grading', to='question_bank.essaysubmission'),
        ),
        migrations.AddField(
            model_name='examsession',
            name='exam_series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='question_bank.examseries'),
        ),
        migrations.AddField(
            model_name='essaysubmission',
            name='exam_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='essay_submissions', to='question_bank.examsession'),
        ),
        migrations.AddField(
            model_name='questionset',
            name='exam_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_sets', to='question_bank.examsession'),
        ),
        migrations.AddField(
            model_name='studyrecommendation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_recommendations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studysession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studysession',
            name='subjects_covered',
            field=models.ManyToManyField(blank=True, related_name='study_sessions', to='question_bank.subject'),
        ),
        migrations.AddField(
            model_name='studyrecommendation',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_recommendations', to='question_bank.subject'),
        ),
        migrations.AddField(
            model_name='questionset',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_sets', to='question_bank.subject', verbose_name='科目'),
        ),
        migrations.AddField(
            model_name='essaysubmission',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='essay_submissions', to='question_bank.subject'),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='exam_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_progress', to='question_bank.examsession'),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='question_bank.question'),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_progress', to='question_bank.subject'),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='examsession',
            unique_together={('exam_series', 'year', 'session')},
        ),
        migrations.AddIndex(
            model_name='studysession',
            index=models.Index(fields=['user', 'started_at'], name='study_sessi_user_id_245ab4_idx'),
        ),
        migrations.AddIndex(
            model_name='studyrecommendation',
            index=models.Index(fields=['user', 'is_read'], name='study_recom_user_id_0b3132_idx'),
        ),
        migrations.AddIndex(
            model_name='studyrecommendation',
            index=models.Index(fields=['user', 'generated_at'], name='study_recom_user_id_43e766_idx'),
        ),
        migrations.AddIndex(
            model_name='essaysubmission',
            index=models.Index(fields=['user', 'subject'], name='essay_submi_user_id_157dcc_idx'),
        ),
        migrations.AddIndex(
            model_name='essaysubmission',
            index=models.Index(fields=['user', 'submitted_at'], name='essay_submi_user_id_f8acf1_idx'),
        ),
        migrations.AddIndex(
            model_name='essaysubmission',
            index=models.Index(fields=['status'], name='essay_submi_status_8720fa_idx'),
        ),
        migrations.AddIndex(
            model_name='userprogress',
            index=models.Index(fields=['user', 'subject'], name='user_progre_user_id_4a9be9_idx'),
        ),
        migrations.AddIndex(
            model_name='userprogress',
            index=models.Index(fields=['user', 'last_attempt_at'], name='user_progre_user_id_787ad1_idx'),
        ),
    ]
