


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";






CREATE TYPE "public"."conversation_role" AS ENUM (
    'user',
    'assistant'
);


ALTER TYPE "public"."conversation_role" OWNER TO "postgres";


CREATE TYPE "public"."question_difficulty" AS ENUM (
    'easy',
    'normal',
    'hard',
    'insane'
);


ALTER TYPE "public"."question_difficulty" OWNER TO "postgres";


CREATE TYPE "public"."question_type" AS ENUM (
    'essay',
    'multipleChoice'
);


ALTER TYPE "public"."question_type" OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."bookmark" (
    "user_id" "uuid" NOT NULL,
    "question_id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."bookmark" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."conversation" (
    "user_id" "uuid" NOT NULL,
    "title" character varying NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"(),
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL
);


ALTER TABLE "public"."conversation" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."conversation_message" (
    "id" bigint NOT NULL,
    "conversation_id" "uuid" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "role" "public"."conversation_role" NOT NULL,
    "content" "text" NOT NULL,
    "reply_to_message_id" bigint
);


ALTER TABLE "public"."conversation_message" OWNER TO "postgres";


ALTER TABLE "public"."conversation_message" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."conversation_id_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."exam" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT ("now"() AT TIME ZONE 'utc'::"text") NOT NULL,
    "updated_at" timestamp with time zone DEFAULT ("now"() AT TIME ZONE 'utc'::"text"),
    "name" character varying NOT NULL,
    "description" character varying,
    "time_limit" smallint DEFAULT '60'::smallint NOT NULL,
    "publish" boolean DEFAULT false NOT NULL,
    "creator" "uuid" NOT NULL
);


ALTER TABLE "public"."exam" OWNER TO "postgres";


ALTER TABLE "public"."exam" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."exam_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."exam_question" (
    "id" bigint NOT NULL,
    "exam_id" bigint,
    "question_id" bigint,
    "order" bigint NOT NULL
);


ALTER TABLE "public"."exam_question" OWNER TO "postgres";


ALTER TABLE "public"."exam_question" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."exam_question_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE "public"."exam_question" ALTER COLUMN "order" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."exam_question_order_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."exam_tag" (
    "exam_id" bigint NOT NULL,
    "tag_id" bigint NOT NULL
);


ALTER TABLE "public"."exam_tag" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."question" (
    "id" bigint NOT NULL,
    "content" character varying,
    "explanation" character varying,
    "type" "public"."question_type" DEFAULT 'multipleChoice'::"public"."question_type" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "creator" "uuid",
    "difficulty" "public"."question_difficulty" DEFAULT 'normal'::"public"."question_difficulty" NOT NULL
);


ALTER TABLE "public"."question" OWNER TO "postgres";


ALTER TABLE "public"."question" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."question_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."question_note" (
    "user_id" "uuid" NOT NULL,
    "question_id" bigint NOT NULL,
    "content" "text" DEFAULT ''::"text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."question_note" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."question_option" (
    "question_id" bigint NOT NULL,
    "content" character varying NOT NULL,
    "is_correct" boolean,
    "order" smallint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."question_option" OWNER TO "postgres";


ALTER TABLE "public"."question_option" ALTER COLUMN "order" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."question_option_order_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."question_tag" (
    "question_id" bigint NOT NULL,
    "tag_id" bigint NOT NULL
);


ALTER TABLE "public"."question_tag" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."tag" (
    "id" bigint NOT NULL,
    "name" character varying NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."tag" OWNER TO "postgres";


ALTER TABLE "public"."tag" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."tag_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY "public"."bookmark"
    ADD CONSTRAINT "bookmark_pkey" PRIMARY KEY ("user_id", "question_id");



ALTER TABLE ONLY "public"."conversation_message"
    ADD CONSTRAINT "conversation_id_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."conversation"
    ADD CONSTRAINT "conversation_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."exam"
    ADD CONSTRAINT "exam_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."exam_question"
    ADD CONSTRAINT "exam_question_order_key" UNIQUE ("order");



ALTER TABLE ONLY "public"."exam_question"
    ADD CONSTRAINT "exam_question_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."exam_tag"
    ADD CONSTRAINT "exam_tag_pkey" PRIMARY KEY ("exam_id", "tag_id");



ALTER TABLE ONLY "public"."question_note"
    ADD CONSTRAINT "question_note_pkey" PRIMARY KEY ("user_id", "question_id");



ALTER TABLE ONLY "public"."question_option"
    ADD CONSTRAINT "question_option_order_key" UNIQUE ("order");



ALTER TABLE ONLY "public"."question_option"
    ADD CONSTRAINT "question_option_pkey" PRIMARY KEY ("question_id", "content");



ALTER TABLE ONLY "public"."question"
    ADD CONSTRAINT "question_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."question_tag"
    ADD CONSTRAINT "question_tag_pkey" PRIMARY KEY ("question_id", "tag_id");



ALTER TABLE ONLY "public"."tag"
    ADD CONSTRAINT "tag_name_key" UNIQUE ("name");



ALTER TABLE ONLY "public"."tag"
    ADD CONSTRAINT "tag_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."bookmark"
    ADD CONSTRAINT "bookmark_question_id_fkey" FOREIGN KEY ("question_id") REFERENCES "public"."question"("id") ON UPDATE RESTRICT ON DELETE CASCADE;



ALTER TABLE ONLY "public"."bookmark"
    ADD CONSTRAINT "bookmark_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON UPDATE RESTRICT ON DELETE CASCADE;



ALTER TABLE ONLY "public"."conversation_message"
    ADD CONSTRAINT "conversation_id_conversation_id_fkey" FOREIGN KEY ("conversation_id") REFERENCES "public"."conversation"("id") ON UPDATE RESTRICT ON DELETE CASCADE;



ALTER TABLE ONLY "public"."conversation_message"
    ADD CONSTRAINT "conversation_message_reply_to_message_id_fkey" FOREIGN KEY ("reply_to_message_id") REFERENCES "public"."conversation_message"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."conversation"
    ADD CONSTRAINT "conversation_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON UPDATE RESTRICT ON DELETE CASCADE;



ALTER TABLE ONLY "public"."exam"
    ADD CONSTRAINT "exam_creator_fkey" FOREIGN KEY ("creator") REFERENCES "auth"."users"("id") ON UPDATE RESTRICT ON DELETE RESTRICT;



ALTER TABLE ONLY "public"."exam_question"
    ADD CONSTRAINT "exam_question_exam_id_fkey" FOREIGN KEY ("exam_id") REFERENCES "public"."exam"("id") ON UPDATE RESTRICT ON DELETE CASCADE;



ALTER TABLE ONLY "public"."exam_question"
    ADD CONSTRAINT "exam_question_question_id_fkey" FOREIGN KEY ("question_id") REFERENCES "public"."question"("id") ON UPDATE RESTRICT ON DELETE CASCADE;



ALTER TABLE ONLY "public"."exam_tag"
    ADD CONSTRAINT "exam_tag_exam_id_fkey" FOREIGN KEY ("exam_id") REFERENCES "public"."exam"("id") ON UPDATE RESTRICT ON DELETE CASCADE;



ALTER TABLE ONLY "public"."exam_tag"
    ADD CONSTRAINT "exam_tag_tag_id_fkey" FOREIGN KEY ("tag_id") REFERENCES "public"."tag"("id") ON UPDATE RESTRICT ON DELETE CASCADE;



ALTER TABLE ONLY "public"."question"
    ADD CONSTRAINT "question_creator_fkey" FOREIGN KEY ("creator") REFERENCES "auth"."users"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."question_note"
    ADD CONSTRAINT "question_note_question_id_fkey" FOREIGN KEY ("question_id") REFERENCES "public"."question"("id") ON UPDATE RESTRICT ON DELETE CASCADE;



ALTER TABLE ONLY "public"."question_note"
    ADD CONSTRAINT "question_note_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON UPDATE RESTRICT ON DELETE CASCADE;



ALTER TABLE ONLY "public"."question_option"
    ADD CONSTRAINT "question_option_question_id_fkey" FOREIGN KEY ("question_id") REFERENCES "public"."question"("id") ON UPDATE RESTRICT ON DELETE CASCADE;



ALTER TABLE ONLY "public"."question_tag"
    ADD CONSTRAINT "question_tag_question_id_fkey" FOREIGN KEY ("question_id") REFERENCES "public"."question"("id") ON UPDATE RESTRICT ON DELETE CASCADE;



ALTER TABLE ONLY "public"."question_tag"
    ADD CONSTRAINT "question_tag_tag_id_fkey" FOREIGN KEY ("tag_id") REFERENCES "public"."tag"("id") ON UPDATE RESTRICT ON DELETE CASCADE;



ALTER TABLE "public"."bookmark" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."conversation" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."conversation_message" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."exam" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."exam_question" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."exam_tag" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."question" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."question_note" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."question_option" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."question_tag" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."tag" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";








































































































































































GRANT ALL ON TABLE "public"."bookmark" TO "anon";
GRANT ALL ON TABLE "public"."bookmark" TO "authenticated";
GRANT ALL ON TABLE "public"."bookmark" TO "service_role";



GRANT ALL ON TABLE "public"."conversation" TO "anon";
GRANT ALL ON TABLE "public"."conversation" TO "authenticated";
GRANT ALL ON TABLE "public"."conversation" TO "service_role";



GRANT ALL ON TABLE "public"."conversation_message" TO "anon";
GRANT ALL ON TABLE "public"."conversation_message" TO "authenticated";
GRANT ALL ON TABLE "public"."conversation_message" TO "service_role";



GRANT ALL ON SEQUENCE "public"."conversation_id_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."conversation_id_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."conversation_id_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."exam" TO "anon";
GRANT ALL ON TABLE "public"."exam" TO "authenticated";
GRANT ALL ON TABLE "public"."exam" TO "service_role";



GRANT ALL ON SEQUENCE "public"."exam_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."exam_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."exam_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."exam_question" TO "anon";
GRANT ALL ON TABLE "public"."exam_question" TO "authenticated";
GRANT ALL ON TABLE "public"."exam_question" TO "service_role";



GRANT ALL ON SEQUENCE "public"."exam_question_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."exam_question_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."exam_question_id_seq" TO "service_role";



GRANT ALL ON SEQUENCE "public"."exam_question_order_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."exam_question_order_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."exam_question_order_seq" TO "service_role";



GRANT ALL ON TABLE "public"."exam_tag" TO "anon";
GRANT ALL ON TABLE "public"."exam_tag" TO "authenticated";
GRANT ALL ON TABLE "public"."exam_tag" TO "service_role";



GRANT ALL ON TABLE "public"."question" TO "anon";
GRANT ALL ON TABLE "public"."question" TO "authenticated";
GRANT ALL ON TABLE "public"."question" TO "service_role";



GRANT ALL ON SEQUENCE "public"."question_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."question_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."question_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."question_note" TO "anon";
GRANT ALL ON TABLE "public"."question_note" TO "authenticated";
GRANT ALL ON TABLE "public"."question_note" TO "service_role";



GRANT ALL ON TABLE "public"."question_option" TO "anon";
GRANT ALL ON TABLE "public"."question_option" TO "authenticated";
GRANT ALL ON TABLE "public"."question_option" TO "service_role";



GRANT ALL ON SEQUENCE "public"."question_option_order_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."question_option_order_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."question_option_order_seq" TO "service_role";



GRANT ALL ON TABLE "public"."question_tag" TO "anon";
GRANT ALL ON TABLE "public"."question_tag" TO "authenticated";
GRANT ALL ON TABLE "public"."question_tag" TO "service_role";



GRANT ALL ON TABLE "public"."tag" TO "anon";
GRANT ALL ON TABLE "public"."tag" TO "authenticated";
GRANT ALL ON TABLE "public"."tag" TO "service_role";



GRANT ALL ON SEQUENCE "public"."tag_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."tag_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."tag_id_seq" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";































drop extension if exists "pg_net";


