# Generated by Django 5.2.7 on 2025-11-24 03:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('free', '免費版'), ('premium', '進階版')], default='free', max_length=20, verbose_name='訂閱等級')),
                ('status', models.CharField(choices=[('active', '有效'), ('cancelled', '已取消'), ('expired', '已過期')], default='active', max_length=20, verbose_name='狀態')),
                ('starts_at', models.DateTimeField(auto_now_add=True, verbose_name='開始時間')),
                ('expires_at', models.DateTimeField(verbose_name='到期時間')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '訂閱',
                'verbose_name_plural': '訂閱',
                'db_table': 'subscription',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='金額')),
                ('currency', models.CharField(default='TWD', max_length=3, verbose_name='幣別')),
                ('status', models.CharField(choices=[('pending', '待處理'), ('completed', '已完成'), ('failed', '失敗'), ('refunded', '已退款')], default='pending', max_length=20, verbose_name='狀態')),
                ('payment_method', models.CharField(max_length=50, verbose_name='付款方式')),
                ('transaction_id', models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='交易ID')),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='Stripe Payment Intent ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='users.subscription')),
            ],
            options={
                'verbose_name': '付款記錄',
                'verbose_name_plural': '付款記錄',
                'db_table': 'payment',
                'ordering': ['-created_at'],
            },
        ),
    ]
