# Generated by Django 5.2.7 on 2025-10-13 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='考卷名稱')),
                ('description', models.TextField(blank=True, verbose_name='考試說明')),
                ('time_limit', models.IntegerField(blank=True, null=True, verbose_name='考試時間限制(分鐘)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='修改時間')),
            ],
            options={
                'verbose_name': '考試',
                'verbose_name_plural': '考試',
                'db_table': 'exam',
                'ordering': ['-created_at'],
            },
        ),
    ]
