# Generated by Django 5.2.7 on 2025-11-24 03:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
        ('question_bank', '0007_essaygrading_essaysubmission_examseries_examsession_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MockExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='測驗名稱')),
                ('question_count', models.IntegerField(default=20, verbose_name='題目數量')),
                ('time_limit', models.IntegerField(blank=True, null=True, verbose_name='時間限制（分鐘）')),
                ('ai_generated', models.BooleanField(default=True, verbose_name='AI 生成')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='生成時間')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mock_exams', to='exams.exam')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mock_exams', to='question_bank.subject', verbose_name='科目')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mock_exams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '模擬測驗',
                'verbose_name_plural': '模擬測驗',
                'db_table': 'mock_exam',
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['user', 'generated_at'], name='mock_exam_user_id_438d03_idx'), models.Index(fields=['subject'], name='mock_exam_subject_86c1cd_idx')],
            },
        ),
    ]
