# Generated by Django 5.2.7 on 2025-11-28 08:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_add_exam_result'),
        ('question_bank', '0008_questiontag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WrongQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wrong_count', models.IntegerField(default=1, verbose_name='錯誤次數')),
                ('last_wrong_at', models.DateTimeField(auto_now=True, verbose_name='最後錯誤時間')),
                ('reviewed', models.BooleanField(default=False, verbose_name='已複習')),
                ('exam_result', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wrong_questions', to='exams.examresult')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wrong_records', to='question_bank.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wrong_questions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '錯題',
                'verbose_name_plural': '錯題',
                'db_table': 'wrong_question',
                'ordering': ['-last_wrong_at'],
                'unique_together': {('user', 'question')},
            },
        ),
    ]
