# Generated by Django 5.2.7 on 2025-12-13 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_add_wrong_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='created_by_admin',
            field=models.BooleanField(default=False, verbose_name='是否為管理員建立'),
        ),
    ]
