# Generated by Django 5.2.7 on 2025-12-15 07:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_exam_created_by_admin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mockexam',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='mockexam',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='mockexam',
            name='user',
        ),
        migrations.AddField(
            model_name='exam',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_exams', to=settings.AUTH_USER_MODEL, verbose_name='建立者'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['created_by', 'created_at'], name='exam_created_f2506d_idx'),
        ),
        migrations.DeleteModel(
            name='MockExam',
        ),
    ]
