# Generated by Django 5.2.7 on 2025-10-13 03:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_review_date', models.DateField(default=django.utils.timezone.now, verbose_name='下次複習日期')),
                ('review_count', models.IntegerField(default=0, verbose_name='複習次數')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
            ],
            options={
                'verbose_name': '快閃卡',
                'verbose_name_plural': '快閃卡',
                'db_table': 'flashcards',
                'ordering': ['next_review_date'],
            },
        ),
    ]
