# Generated by Django 5.2.7 on 2025-10-13 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flashcards', '0001_initial'),
        ('question_bank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to='question_bank.question', verbose_name='題目'),
        ),
    ]
