# Generated by Django 5.2.7 on 2025-11-28 08:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0004_spaced_repetition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='next_review_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='下次複習日期'),
        ),
    ]
